services:
  db:
    image: postgres:17
    container_name: internship_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: internship_db

    ports:
      - "5544:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./Backend
    container_name: internship_backend

    ports:
      - "5000:5000"

    env_file:
      - ./Backend/.env

    depends_on:
      - db

    volumes:
      - ./Backend:/app
      - /app/node_modules

    environment:
      CHOKIDAR_USEPOLLING: "true"

  frontend:
    build: ./Frontend
    container_name: internship_frontend

    ports:
      - "5173:5173"

    volumes:
      - ./Frontend:/app
      - /app/node_modules

    environment:
      CHOKIDAR_USEPOLLING: "true"

volumes:
  postgres_data: